version: '3'

services:
  postgres:    
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orders
    ports:
        - "5432:5432"
    expose:
        - 5432
    volumes:
        - .data:/var/lib/postgresql/data
        - .setup/sql/create_table.sql:/docker-entrypoint-initdb.d/init.sql              
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest            
    volumes:
      - ./setup/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./setup/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./setup/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
                    

