version: '3'

services:
  postgres:    
    image: postgres:14.1-alpine
    container_name: postgres
    restart: always
    tty: true
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=orders
    ports:
        - "5432:5432"
    expose:
        - 5432
    volumes:
        - ./setup/sql/create_table.sql:/docker-entrypoint-initdb.d/init.sql             
        - .data:/var/lib/postgresql/data  
    networks:
        - ordersystem
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest            
    volumes:
      - ./setup/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./setup/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./setup/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
    networks:
        - ordersystem
  api:
      container_name: api 
      #build: .  
      image: allancordeiros/pos-fc-clean-arch:latest
      hostname: api
      restart: always          
      depends_on:
        - postgres    
        - rabbitmq  
      networks:
        - ordersystem
      ports:
        - 8000:8000
        - 8080:8080
        - 50051:50051
networks:
  ordersystem: